---
name: Update Transcript Daily

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  update-transcript:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing changes to the repository
      actions: write   # Allow triggering other workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update transcript data
        env:
          LOCALE: ${{ vars.LOCALE }}
        run: |
          python passed_exams.py "${{ secrets.TRANSCRIPT_CODE }}" \
            --output passed_exams.csv

      - name: Commit and push changes
        id: commit_changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add passed_exams.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Update passed_exams.csv with latest transcript data"
            git push
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Azure Static Web Apps deployment
        if: steps.commit_changes.outputs.changes_made == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'azure-static-web-apps-purple-pond-0cdaaa710.yml',
              ref: 'main'
            });